### ISSUE TITLE
Slowness/Bad Connection error on website.

### ISSUE THREAD

**Issue by JamieMikami** [csgpro/csgpro.com#155]
Ron posted a blog to a tweet and kept getting an error.  I then went to the site and it was really slow and then got a 50/50 response of the below error and general slowness.  Now it seems to be fine.

https://twitter.com/ronellisgaut
https://t.co/8jA0Geb7OO
https://www.csgpro.com/blog/2016/09/using-direct-query-a-tale-from-the-trenches

Error: Bad Connection
    at null. (D:\home\site\wwwroot\dist\controllers\blog.controller.js:86:24)
    at bound (domain.js:287:14)
    at runBound (domain.js:300:12)
    at tryCatcher (D:\home\site\wwwroot\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (D:\home\site\wwwroot\node_modules\bluebird\js\release\promise.js:504:31)
    at Promise._settlePromise (D:\home\site\wwwroot\node_modules\bluebird\js\release\promise.js:561:18)
    at Promise._settlePromise0 (D:\home\site\wwwroot\node_modules\bluebird\js\release\promise.js:606:10)
    at Promise._settlePromises (D:\home\site\wwwroot\node_modules\bluebird\js\release\promise.js:681:18)
    at Async._drainQueue (D:\home\site\wwwroot\node_modules\bluebird\js\release\async.js:138:16)
    at Async._drainQueues (D:\home\site\wwwroot\node_modules\bluebird\js\release\async.js:148:10)
    at Immediate.Async.drainQueues [as _onImmediate] (D:\home\site\wwwroot\node_modules\bluebird\js\release\async.js:17:14)
    at processImmediate [as _immediateCallback] (timers.js:383:17)
Status Code: 500

**Comment by kenhowardpdx** [comment]
```
Starting at approximately 18:31 UTC on 30 Sep 2016, customers using SQL Database in the West US region may experience issues performing service management operations. Server and Database create, drop, rename and change edition or performance tier operations may not complete successfully. Customers may see availability issues (connecting to and using existing databases), and retries may be successful. We recommend customers who are impacted and have geo-replication for their SQL Databases to failover. Azure Data Movement services deployed in the region may also experience issues accessing monitoring. Web Apps deployed to the region may also experience latency and API Management failures. Engineers are currently investigating mitigation steps and the next update will be provided in 60 minutes.
```

Further details: https://azure.microsoft.com/en-us/status/history/

Azure will provide a post incident report in ~48 hours.
